<?php

use Drupal\autonumber\FieldProcessor\Processor;
use Drupal\Core\Entity\ContentEntityBase;

/**
 * Implements hook_entity_presave().
 */
function autonumber_entity_presave($entity) {
  /** @var \Drupal\Core\Entity\ContentEntityInterface $entity */
  if (!$entity instanceof ContentEntityBase) {
    return;
  }

  foreach ($entity->getFields() as $fieldName => $field) {
    $fieldDefinition = $field->getFieldDefinition();
    // Only fields of type autonumber need to be configured
    if ($fieldDefinition->getType() !== 'autonumber') {
      continue;
    }

    $doProcess = \Drupal::moduleHandler()->invokeAll('autonumber_should_process', [
      'entity' => $entity,
      'field' => $fieldDefinition,
    ]);

    if (in_array(FALSE, $doProcess)) {
      continue;
    }

    (new Processor($entity, $fieldDefinition))->process();
  }
}

/**
 * Implements hook_theme().
 */
function autonumber_theme() {
  // Register the theme for the autonumber default.
  return [
    'autonumber_default' => [
      'variables' => [
        'autonumber_id' => NULL,
      ],
    ],
  ];
}

/**
 * Implements hook_help().
 */
function autonumber_help($route_name, $route_match) {
  switch ($route_name) {
    case 'help.page.autonumber':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Defines autonumber field type.') . '</p>';
      return $output;
  }
}

/**
 * Theme function for the autonumber default.
 *
 * @param array $variables
 *   Theme variables.
 *
 * @return array
 *   Theme variables.
 */
function theme_autonumber_default(array $variables) {
  return $variables['autonumber_id'];
}
